language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
env:
    - TORNADO_VERSION=3.2.2
    - TORNADO_VERSION=4.4.2
install:
    - "pip install -r requirements.txt"
    - "pip install tornado>=$TORNADO_VERSION"
    - "pip install pytest"
    - "pip install pytest-cov"
    - "pip install coverage"
    - "pip install coveralls"
    - "pip install mock"
script:
    coverage run --source=tornado_json setup.py test
after_success:
    coveralls --verbose
